#!/usr/bin/env bash
source $HOME/.owl4ce_var

noterr() { $EXNOTIFY_SEND -u low -r 16 "Install brightnessctl!"; exit 1; }
command -v "brightnessctl" > /dev/null 2>&1 || noterr

notify() {
    BRIGHTNESS="$(brightnessctl i | grep '%' | awk -F'(' '{print $2}' | awk -F'%' '{print $1}')"
    
    if [[ "$BRIGHTNESS" = "0" ]]; then
        icon_name="notification-display-brightness-off"
    elif [[ "$BRIGHTNESS" -lt "10" ]]; then
        icon_name="notification-display-brightness-low"
    elif [[ "$BRIGHTNESS" -lt "30" ]]; then
        icon_name="notification-display-brightness-medium"
    elif [[ "$BRIGHTNESS" -lt "70" ]]; then
        icon_name="notification-display-brightness-medium"
    elif [[ "$BRIGHTNESS" -lt "100" ]]; then
        icon_name="notification-display-brightness-high"
    else
        icon_name="notification-display-brightness-full"
    fi
    
    $EXNOTIFY_SEND -i "$icon_name" -t 700 -r 1234 "$BRIGHTNESS "
}

case $1 in
    up)         brightnessctl set "$BRIGHTNESS_STEPS"%+ -q
                notify
	;;
    down)       brightnessctl set "$BRIGHTNESS_STEPS"%- -q
                notify
	;;
    optimal)    brightnessctl set 25% -q
                notify
	;;
esac    
