#!/usr/bin/env bash
source $HOME/.owl4ce_var

CURRENT_BRIGHTNESS() { brightnessctl i | grep '%' | awk -F'(' '{print $2}' | awk -F'%' '{print $1}'; }

notify() {
    brightness="$(CURRENT_BRIGHTNESS)"
    
    if [ "$brightness" = "0" ]; then
        icon_name="notification-display-brightness-off"
    else    
        if [  "$brightness" -lt "10" ]; then
            icon_name="notification-display-brightness-low"
        else
            if [ "$brightness" -lt "30" ]; then
                icon_name="notification-display-brightness-medium"
            else
                if [ "$brightness" -lt "70" ]; then
                    icon_name="notification-display-brightness-medium"
                else
                    if [ "$brightness" -lt "100" ]; then
                        icon_name="notification-display-brightness-high"
                    else
                        icon_name="notification-display-brightness-full"
                    fi
                fi
            fi
        fi
    fi
    $EXNOTIFY_SEND -i "$icon_name" -t 2000 -r 1234 "$brightness "
}

case $1 in
    up)
        # +5%
        brightnessctl set $BRIGHTNESS_STEPS%+ -q
        notify
	;;
    down)
        # -5%
        brightnessctl set $BRIGHTNESS_STEPS%- -q
        notify
	;;
    optimal)
        # Toggle optimal
        brightnessctl set 25% -q
        notify
	;;
esac    
