#!/usr/bin/env bash
LC_ALL=C LANG=C; source "$HOME"/.owl4ce_var
echo "$CHK_ORT" > "${VISMOD_ROFI_FILE}.${STATE_EXT:-joy}"

OB_MARGIN="10"

case $1 in
    v_left)     sed -s -i 's_geometry =.*_geometry = "350x6-19+52"_' "$DUNST_DIR"/dunstrc-{mech,eyc}
                
                sed -s -i 's_anchor:.*_anchor: east;_' "$ROFI_SIDEBAR_DIR"/*-vertical.rasi
                sed -s -i 's_location:.*_location: east;_' "$ROFI_SIDEBAR_DIR"/*-vertical.rasi
                sed -s -i 's_x-offset:.*_x-offset: -1.4%;_' "$ROFI_SIDEBAR_DIR"/*-vertical.rasi
                
                sed -i "131s_<right>.*_<right>${OB_MARGIN}</right>_" "$OB_CONFIG"
                sed -i "130s_<left>.*_<left>$((45 + ${OB_MARGIN}))</left>_" "$OB_CONFIG"
                sed -i "129s_<bottom>.*_<bottom>${OB_MARGIN}</bottom>_" "$OB_CONFIG"
                sed -i "128s_<top>.*_<top>${OB_MARGIN}</top>_" "$OB_CONFIG"
    ;;
    v_right)    sed -s -i 's_geometry =.*_geometry = "350x6+19+52"_' "$DUNST_DIR"/dunstrc-{mech,eyc}
                
                sed -s -i 's_anchor:.*_anchor: west;_' "$ROFI_SIDEBAR_DIR"/*-vertical.rasi
                sed -s -i 's_location:.*_location: west;_' "$ROFI_SIDEBAR_DIR"/*-vertical.rasi
                sed -s -i 's_x-offset:.*_x-offset: 1.4%;_' "$ROFI_SIDEBAR_DIR"/*-vertical.rasi
                
                sed -i "131s_<right>.*_<right>$((45 + ${OB_MARGIN}))</right>_" "$OB_CONFIG"
                sed -i "130s_<left>.*_<left>${OB_MARGIN}</left>_" "$OB_CONFIG"
                sed -i "129s_<bottom>.*_<bottom>${OB_MARGIN}</bottom>_" "$OB_CONFIG"
                sed -i "128s_<top>.*_<top>${OB_MARGIN}</top>_" "$OB_CONFIG"
    ;;
    h_top)      sed -s -i 's_geometry =.*_geometry = "350x6+19+65"_' "$DUNST_DIR"/dunstrc-{mech,eyc}
                
                sed -s -i 's_anchor:.*_anchor: south;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
                sed -s -i 's_location:.*_location: south;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
                sed -s -i 's_y-offset:.*_y-offset: -3%;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
                
                sed -i "131s_<right>.*_<right>${OB_MARGIN}</right>_" "$OB_CONFIG"
                sed -i "130s_<left>.*_<left>${OB_MARGIN}</left>_" "$OB_CONFIG"
                sed -i "129s_<bottom>.*_<bottom>${OB_MARGIN}</bottom>_" "$OB_CONFIG"
                sed -i "128s_<top>.*_<top>$((45 + ${OB_MARGIN}))</top>_" "$OB_CONFIG"
    ;;
    h_bottom)   sed -s -i 's_geometry =.*_geometry = "350x6-19+52"_' "$DUNST_DIR"/dunstrc-{mech,eyc}
                
                sed -s -i 's_anchor:.*_anchor: north;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
                sed -s -i 's_location:.*_location: north;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
                sed -s -i 's_y-offset:.*_y-offset: 6.9%;_' "$ROFI_SIDEBAR_DIR"/*-horizontal.rasi
                
                sed -i "131s_<right>.*_<right>${OB_MARGIN}</right>_" "$OB_CONFIG"
                sed -i "130s_<left>.*_<left>${OB_MARGIN}</left>_" "$OB_CONFIG"
                sed -i "129s_<bottom>.*_<bottom>$((45 + ${OB_MARGIN}))</bottom>_" "$OB_CONFIG"
                sed -i "128s_<top>.*_<top>${OB_MARGIN}</top>_" "$OB_CONFIG"
    ;;
    minmod)     sed -i "131s_<right>.*_<right>${OB_MARGIN}</right>_" "$OB_CONFIG"
                sed -i "130s_<left>.*_<left>${OB_MARGIN}</left>_" "$OB_CONFIG"
                sed -i "129s_<bottom>.*_<bottom>${OB_MARGIN}</bottom>_" "$OB_CONFIG"
                sed -i "128s_<top>.*_<top>$((30 + ${OB_MARGIN}))</top>_" "$OB_CONFIG"
    ;;
esac; exit $?
