#!/usr/bin/env bash
source $HOME/.owl4ce_var

kill() { { killall tint2; killall dunst; [[ "$1" = "also_tray" ]] && killall $CHK_TRAY; } &> /dev/null; }

mechanical() {
    # Write Current
    echo "mechanical" > $MOD_FILE
    # Set Theme & UI
    ( "$VISMOD_DIR/mechanical/theme" && "$VISMOD_DIR/UI" ) &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_MECH_ICON" "Visual Mode" "Mechanical Theme applied"
}

mechanical_min() {
    # Write Current
    echo "mechanical" > $MOD_FILE && echo "minimal" >> $MOD_FILE
    # Set Theme & UI
    ( "$VISMOD_DIR/mechanical/theme-minimal" && "$VISMOD_DIR/UI" minimal ) &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_MECH_MIN_ICON" "Minimal Mode" "Mechanical Theme enabled"
}

eyecandy() {
    # Write Current
    echo "eyecandy" > $MOD_FILE
    # Set Theme & UI
    ( "$VISMOD_DIR/eyecandy/theme" && "$VISMOD_DIR/UI" ) &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_EYC_ICON" "Visual Mode" "Eyecandy Theme applied"
}

eyecandy_min() {
    # Write Current
    echo "eyecandy" > $MOD_FILE && echo "minimal" >> $MOD_FILE
    # Set Theme & UI
    ( "$VISMOD_DIR/eyecandy/theme-minimal" && "$VISMOD_DIR/UI" minimal ) &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_EYC_MIN_ICON" "Minimal Mode" "Eyecandy Theme enabled"
}

case $1 in
    minimal)    source $HOME/.owl4ce_var && kill also_tray
                MINMOD="" && [[ -z $CHK_MINMOD ]] && MINMOD="_min"
                "$CHK_VISMOD$MINMOD"
                "$OB_TRAY" &> /dev/null
    ;;
    just_ui)    source $HOME/.owl4ce_var && xrdb $HOME/.Xresources && kill
                ISMIN="" && [[ ! -z $CHK_MINMOD ]] && ISMIN=" minimal"
                "$VISMOD_DIR/UI$ISMIN" &> /dev/null
    ;;
    *)          source $HOME/.owl4ce_var && kill also_tray
                MINMOD="" && [[ ! -z $CHK_MINMOD ]] && MINMOD="_min"
                if [[ $CHK_VISMOD != *"mechanical"* ]]; then
                    "mechanical$MINMOD"
                elif [[ $CHK_VISMOD != *"eyecandy"* ]]; then
                    "eyecandy$MINMOD"
                fi
                "$OB_TRAY" &> /dev/null
	;;
esac
