#!/usr/bin/env bash
source $HOME/.owl4ce_var

kill() { killall tint2; killall $CHK_TRAY &> /dev/null; killall dunst; }

mech() {
    # Write Current
    echo "mechanical" > $MOD_FILE
    # Set Theme & UI
    bash -c "$VISMOD_DIR/mechanical/theme"
    bash -c "$VISMOD_DIR/mechanical/ui" &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_MECH_ICON" "Visual Mode" "Mechanical Theme applied"
}

mech_min() {
    # Write Current
    echo "mechanical" > $MOD_FILE && echo "minimal" >> $MOD_FILE
    # Set Theme & UI
    bash -c "$VISMOD_DIR/mechanical/theme-minimal"
    bash -c "$VISMOD_DIR/mechanical/ui-minimal" &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_MECH_MIN_ICON" "Minimal Mode" "Mechanical Theme enabled"
}

eyc() {
    # Write Current
    echo "eyecandy" > $MOD_FILE
    # Set Theme & UI
    bash -c "$VISMOD_DIR/eyecandy/theme"
    bash -c "$VISMOD_DIR/eyecandy/ui" &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_EYC_ICON" "Visual Mode" "Eyecandy Theme applied"
}

eyc_min() {
    # Write Current
    echo "eyecandy" > $MOD_FILE && echo "minimal" >> $MOD_FILE
    # Set Theme & UI
    bash -c "$VISMOD_DIR/eyecandy/theme-minimal"
    bash -c "$VISMOD_DIR/eyecandy/ui-minimal" &> /dev/null
    # Notify Success
    notify-send -u low -i "$NOTIF_EYC_MIN_ICON" "Minimal Mode" "Eyecandy Theme enabled"
}

case $1 in
    minimal)    source $HOME/.owl4ce_var && kill
                if [[ $CHK_VISMOD = *"mechanical"* ]]; then
                    MINMOD="_min" && [[ $CHK_MINMOD != "" ]] && MINMOD=""
                    mech$MINMOD
                elif [[ $CHK_VISMOD = *"eyecandy"* ]]; then
                    MINMOD="_min" && [[ $CHK_MINMOD != "" ]] && MINMOD=""
                    eyc$MINMOD
                fi
    ;;
    startup)    source $HOME/.owl4ce_var
                xrdb $HOME/.Xresources
                MINMOD="" && [[ $CHK_MINMOD != "" ]] && MINMOD="-minmod"
                bash -c "$VISMOD_DIR/$CHK_VISMOD/ui$MINMOD" &> /dev/null
    ;;
    *)          source $HOME/.owl4ce_var && kill
                MINMOD="" && [[ $CHK_MINMOD != "" ]] && MINMOD="_min"
                if [[ $CHK_VISMOD != *"mechanical"* ]]; then
                    mech$MINMOD
                elif [[ $CHK_VISMOD != *"eyecandy"* ]]; then
                    eyc$MINMOD
                fi
	;;
esac    

# Start Tray
bash -c "$OB_TRAY" &> /dev/null
