#!/usr/bin/env bash
LC_ALL=C LANG=C; . "${HOME}/.owl4ce_var"

case ${1} in
    swap)  [[ -n "$CHK_MINMOD" ]] && BTN_LOC="$MINMOD_LOC_BUTTON_FILE" || BTN_LOC="$VISMOD_LOC_BUTTON_FILE"
           if [[ "$CHK_OB_BUTTON_LOC" != "<titleLayout>LIMC</titleLayout>" ]]; then
               sed -i '/<titleLayout>/s/>.*</>LIMC</' "$OB_CONFIG"
               echo "right" > "$BTN_LOC" 
           elif [[ "$CHK_OB_BUTTON_LOC" != "<titleLayout>CIML</titleLayout>" ]]; then
               sed -i '/<titleLayout>/s/>.*</>CIML</' "$OB_CONFIG"
               echo "left" > "$BTN_LOC"
           fi && exec openbox --reconfigure
    ;;
    decor) DECOR_LINE="$(($(cat -n "$OB_CONFIG" | grep '<application class="\*" type="normal">' | grep -oE '[0-9]+')+1))"
           if cat -n "$OB_CONFIG" | grep -qo "${DECOR_LINE}	        <decor>yes</decor>"; then
               sed -i "${DECOR_LINE}s_<decor>.*</decor>_<decor>no</decor>_" "$OB_CONFIG"
           elif cat -n "$OB_CONFIG" | grep -qo "${DECOR_LINE}	        <decor>no</decor>"; then
               sed -i "${DECOR_LINE}s_<decor>.*</decor>_<decor>yes</decor>_" "$OB_CONFIG"
           fi && exec openbox --reconfigure --restart
    ;;
    *)     RB="\e[5;31m" GB="\e[5;32m" Y="\e[1;33m" M="\e[1;35m" C="\e[1;36m" W="\e[1;37m" NC="\e[0m" r="\e[0;31m"
           [[ -n "$CHK_MINMOD" ]] && CAP="$(echo "${CHK_MINMOD} " | sed 's/.*/\u&/')" || :
           CAP="${CAP}$(echo "$CHK_VISMOD" | sed 's/.*/\u&/')" # This is capitalization area.
           n=0; printf "\ec${C}-${GB}-${NC}${C}- ${W}Select button style for ${CAP} Theme${NC}\n"
           for button in "$OB_BUTTON_DIR"/*; do
               n="$((n+1))"
               btnflt="$(echo "$button" | grep -oE '[^/]+$')"
               printf "${M}[${NC}%s${M}] ${r}%s\n" "$n" "$btnflt"
               eval "button${n}=\$button"
           done
           printf "${C}-${GB}-${NC}${C}- ${W}Enter File Index ID ${M}[${NC}1${M}] ${W}to ${M}[${NC}%s${M}]${W}: ${NC}" "$n"
           read -r num; num="$(printf '%s\n' "$num" | tr -dc '[:digit:]')"
           if [[ "$num" -eq 0 || "$num" -gt "$n" ]]; then
               >&2 printf "${Y}[${RB}!${NC}${Y}] ${RB}Wrong selection :(\n"
               exit 1
           else
               eval "BTN=\$button${num}" # Write the selected.
               [[ "$CHK_VISMOD" = "mechanical" ]] && BTN_DIR="$MECH_BUTTON_DIR" || :
               [[ "$CHK_VISMOD" = "eyecandy" ]] && BTN_DIR="$EYC_BUTTON_DIR" || :
               cp -f "$BTN"/* "$BTN_DIR"/. && openbox --reconfigure || exit 1
               selected="$(echo "$BTN" | grep -oE '[^/]+$')"
               [[ -n "$CHK_MINMOD" ]] && BTN_FILE="$MINMOD_BUTTON_FILE" \
               || BTN_FILE="$VISMOD_BUTTON_FILE"; echo "$selected" > "$BTN_FILE"
               printf "${C}[${GB}√${NC}${C}] ${W}Selected button style: ${r}${selected}\n"
           fi
    ;;
esac

exit $?
