#!/usr/bin/env bash
. "${HOME}/.owl4ce_var"

if [ -z "$CHK_MINMOD" ]; then
    killall tint2 dunst &>/dev/null
    case ${1} in
        lrtb) if [ "$CHK_ORT" = 'vertical' ]; then
                  if [ "$CHK_ORT_V" != 'left' ]; then
                      sed -i '/vertical=/s/".*"/"left"/' "$ORT_FILE"
                      "${VISMOD_DIR}/margin-dunst-rofi" v_left
                      sed -si '/panel_position/s/= center .* vertical/= center left vertical/' "$TINT2_DIR"/*-"${CHK_ORT}.tint2rc"
                  elif [ "$CHK_ORT_V" != 'right' ]; then
                      sed -i '/vertical=/s/".*"/"right"/' "$ORT_FILE"
                      "${VISMOD_DIR}/margin-dunst-rofi" v_right
                      sed -si '/panel_position/s/= center .* vertical/= center right vertical/' "$TINT2_DIR"/*-"${CHK_ORT}.tint2rc"
                  fi
              elif [ "$CHK_ORT" = 'horizontal' ]; then
                  if [ "$CHK_ORT_H" != 'bottom' ]; then
                      sed -i '/horizontal=/s/".*"/"bottom"/' "$ORT_FILE"
                      "${VISMOD_DIR}/margin-dunst-rofi" h_bottom
                      sed -si '/panel_position/s/= .* center horizontal/= bottom center horizontal/' "$TINT2_DIR"/*-"${CHK_ORT}.tint2rc"
                  elif [ "$CHK_ORT_H" != 'top' ]; then
                      sed -i '/horizontal=/s/".*"/"top"/' "$ORT_FILE"
                      "${VISMOD_DIR}/margin-dunst-rofi" h_top
                      sed -si '/panel_position/s/= .* center horizontal/= top center horizontal/' "$TINT2_DIR"/*-"${CHK_ORT}.tint2rc"
                  fi
              fi
        ;;
        ort)  if [ "$CHK_ORT" != 'vertical' ]; then
                  sed -e "/vertical=/s/\".*\"/\"${CHK_ORT_V}\"/" \
                      -e '/state=/s/".*"/"vertical"/' -i "$ORT_FILE"
                  "${VISMOD_DIR}/margin-dunst-rofi" v_${CHK_ORT_V}
                  sed -si "/panel_position/s/= center .* vertical/= center ${CHK_ORT_V} vertical/" "$TINT2_DIR"/*-"${CHK_ORT}.tint2rc"
              elif [ "$CHK_ORT" != 'horizontal' ]; then
                  sed -e "/horizontal=/s/\".*\"/\"${CHK_ORT_H}\"/" \
                      -e '/state=/s/".*"/"horizontal"/' -i "$ORT_FILE"
                  "${VISMOD_DIR}/margin-dunst-rofi" h_${CHK_ORT_H}
                  sed -si "/panel_position/s/= center .* horizontal/= center ${CHK_ORT_V} horizontal/" "$TINT2_DIR"/*-"${CHK_ORT}.tint2rc"
              fi
        ;;
    esac
    { openbox --reconfigure && exec "${VISMOD_DIR}/UI" partially; } &>/dev/null
fi

exit ${?}
