#!/usr/bin/env bash

# Start Eyecandy Theme

current="$(cat ~/.config/openbox/visual-mode/current)"

if [[ $current != *"eyecandy"* ]]; then
    
    # Kill Current
    bash -c '~/.config/openbox/visual-mode/kill-ui'
    
    # Set Theme & UI
    bash -c '~/.config/openbox/visual-mode/eyecandy/theme'
    bash -c '~/.config/openbox/visual-mode/eyecandy/ui'
    
    # Tray
    bash -c '~/.config/openbox/tray'
    
    # Write Current
    echo "eyecandy" > ~/.config/openbox/visual-mode/current

    # Notify Success
    notify-send -u low -i lookswitcher "Visual Mode" "Eyecandy Theme applied"

else

    # Notify Fail
    notify-send -u low -i lookswitcher "Visual Mode" "You're already in Eyecandy Theme"
    
fi
