#!/usr/bin/env bash

# SLiM background synchronizing

current="$(cat ~/.config/openbox/visual-mode/current)"
chkmin="$(cat ~/.config/openbox/visual-mode/current | grep 'minimal')"
icon="~/.icons/gladient/slimsync.png"

if [[ $chkmin = *"minimal"* ]]; then
    if [[ $current = *"mechanical"* ]]; then
        # Minimal Mechanical Theme
        notify-send -i $icon "SLiM Background" "Synchronize current wallpaper" &
        wall="$(cat ~/.config/openbox/visual-mode/mechanical/wall-minimal)"
        convert ~/.wallpaper/mechanical/$wall -resize 1920x1080 -blur 0x80 ~/.wallpaper/slim.png && \
        notify-send -u low -i $icon "SLiM Background" "Synchronized successfully" &
    else
        # Minimal Eyecandy Theme
        notify-send -i $icon "SLiM Background" "Synchronize current wallpaper" &
        wall="$(cat ~/.config/openbox/visual-mode/eyecandy/wall-minimal)"
        convert ~/.wallpaper/eyecandy/$wall -resize 1920x1080 -blur 0x80 ~/.wallpaper/slim.png && \
        notify-send -u low -i $icon "SLiM Background" "Synchronized successfully" &
    fi
else
    if [[ $current = *"mechanical"* ]]; then
        # Mechanical Theme
        notify-send -i $icon "SLiM Background" "Synchronize current wallpaper" &
        wall="$(cat ~/.config/openbox/visual-mode/mechanical/wall)"
        convert ~/.wallpaper/mechanical/$wall -resize 1920x1080 -blur 0x80 ~/.wallpaper/slim.png && \
        notify-send -u low -i $icon "SLiM Background" "Synchronized successfully" &
    else
        # Eyecandy Theme
        notify-send -i $icon "SLiM Background" "Synchronize current wallpaper" &
        wall="$(cat ~/.config/openbox/visual-mode/eyecandy/wall)"
        convert ~/.wallpaper/eyecandy/$wall -resize 1920x1080 -blur 0x80 ~/.wallpaper/slim.png && \
        notify-send -u low -i $icon "SLiM Background" "Synchronized successfully" &
    fi
fi
