#!/usr/bin/env bash
LC_ALL=C LANG=C source $HOME/.owl4ce_var

noterr() { $EXNOTIFY_SEND -u low -r 14 "Install rxvt-unicode/termite!"; exit 1; }
command -v {"urxvt","termite"} &> /dev/null || noterr

# Set URxvt Icon File Automatically and set URxvt URL Launcher from owl4ce_var
sed -i "s_URxvt.iconFile:.*_URxvt.iconFile:                   ${TERM_ICON}_" $XRESOURCES_CONFIG
sed -i "s_URxvt.url-select.launcher:.*_URxvt.url-select.launcher:        ${WEB_BROWSER}_" $XRESOURCES_CONFIG
    
TRANS() {
    if [[ "${URXVT:-100}" -lt 100 ]]; then
        sed -i "s_URxvt.depth:.*_URxvt.depth:                      32_" $XRESOURCES_CONFIG
    else
        sed -i "s_URxvt.depth:.*_URxvt.depth:                      24_" $XRESOURCES_CONFIG
    fi
    case $1 in
        apply)  if [[  "$current" != *"!"* ]]; then
                    sed -i "68s_\[.*\]_\[${URXVT:-100}\]_" $XRESOURCES_CONFIG
                    sed -i "84s_\[.*\]_\[100\]_" $XRESOURCES_CONFIG
                else
                    sed -i "68s_\[.*\]_\[100\]_" $XRESOURCES_CONFIG
                    sed -i "84s_\[.*\]_\[${URXVT:-100}\]_" $XRESOURCES_CONFIG
                fi
        ;;
        invert) if [[  "$current" = *"!"* ]]; then
                    sed -i "68s_\[.*\]_\[${URXVT:-100}\]_" $XRESOURCES_CONFIG
                    sed -i "84s_\[.*\]_\[100\]_" $XRESOURCES_CONFIG
                else
                    sed -i "68s_\[.*\]_\[100\]_" $XRESOURCES_CONFIG
                    sed -i "84s_\[.*\]_\[${URXVT:-100}\]_" $XRESOURCES_CONFIG
                fi
        ;;
    esac
}

if [[ "$($DEFAPPS_EXEC -g terminal)" = "urxvt" ]]; then
    current="$(cat "$XRESOURCES_CONFIG" | grep 'foreground' | head -n1 | grep '!')"
    case $1 in
        trans)  TRANS apply
        ;;
        *)      TRANS invert
                if [[  "$current" != *"!"* ]]; then
                    sed -i '103s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '104s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '105s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '107s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '108s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '110s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '111s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '113s_!__' $XRESOURCES_CONFIG
                    sed -i '114s_!__' $XRESOURCES_CONFIG
                    sed -i '115s_!__' $XRESOURCES_CONFIG
                    sed -i '117s_!__' $XRESOURCES_CONFIG
                    sed -i '118s_!__' $XRESOURCES_CONFIG
                    sed -i '120s_!__' $XRESOURCES_CONFIG
                    sed -i '121s_!__' $XRESOURCES_CONFIG
                else
                    sed -i '103s_!__' $XRESOURCES_CONFIG
                    sed -i '104s_!__' $XRESOURCES_CONFIG
                    sed -i '105s_!__' $XRESOURCES_CONFIG
                    sed -i '107s_!__' $XRESOURCES_CONFIG
                    sed -i '108s_!__' $XRESOURCES_CONFIG
                    sed -i '110s_!__' $XRESOURCES_CONFIG
                    sed -i '111s_!__' $XRESOURCES_CONFIG
                    sed -i '113s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '114s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '115s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '117s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '118s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '120s_*_!*_' $XRESOURCES_CONFIG
                    sed -i '121s_*_!*_' $XRESOURCES_CONFIG
                fi
            ;;
        esac
        xrdb $XRESOURCES_CONFIG &
elif [[ "$($DEFAPPS_EXEC -g terminal)" = "termite" ]]; then
    current="$(cat "$TERMITE_CONFIG" | grep '#foreground = ' | head -n1)"
    if [[  "$current" != *"#foreground = #F9F9F9"* ]]; then
        sed -i '79s_foreground_#foreground_' $TERMITE_CONFIG
        sed -i '80s_foreground_#foreground_' $TERMITE_CONFIG
        sed -i '81s_background_#background_' $TERMITE_CONFIG
        sed -i '90s_#foreground_foreground_' $TERMITE_CONFIG
        sed -i '91s_#foreground_foreground_' $TERMITE_CONFIG
        sed -i '92s_#background_background_' $TERMITE_CONFIG
        sed -i '93s_color_#color_' $TERMITE_CONFIG
        sed -i '94s_color_#color_' $TERMITE_CONFIG
        sed -i '86s_color_#color_' $TERMITE_CONFIG
        sed -i '87s_color_#color_' $TERMITE_CONFIG
        sed -i '94s_#color_color_' $TERMITE_CONFIG
        sed -i '95s_#color_color_' $TERMITE_CONFIG
        sed -i '97s_#color_color_' $TERMITE_CONFIG
        sed -i '98s_#color_color_' $TERMITE_CONFIG
    else
        sed -i '79s_#foreground_foreground_' $TERMITE_CONFIG
        sed -i '80s_#foreground_foreground_' $TERMITE_CONFIG
        sed -i '81s_#background_background_' $TERMITE_CONFIG
        sed -i '90s_foreground_#foreground_' $TERMITE_CONFIG
        sed -i '91s_foreground_#foreground_' $TERMITE_CONFIG
        sed -i '92s_background_#background_' $TERMITE_CONFIG
        sed -i '93s_#color_color_' $TERMITE_CONFIG
        sed -i '94s_#color_color_' $TERMITE_CONFIG
        sed -i '86s_#color_color_' $TERMITE_CONFIG
        sed -i '87s_#color_color_' $TERMITE_CONFIG
        sed -i '94s_color_#color_' $TERMITE_CONFIG
        sed -i '95s_color_#color_' $TERMITE_CONFIG
        sed -i '97s_color_#color_' $TERMITE_CONFIG
        sed -i '98s_color_#color_' $TERMITE_CONFIG
    fi
fi
