#!/usr/bin/env bash

MUSIC_DIR="$(cat ~/.ncmpcpp/albumart-only | grep 'mpd_music_dir' | awk -F'"' '{print $2}')"
COVER="/tmp/cover.jpg"

function reset_background
{
    printf "\e]20;;100x100+1000+1000\a"
}

{
    album="$(mpc --format %album% current -p 6600)"
    file="$(mpc --format %file% current -p 6600)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    
    # Album Art
    if [[ -n "$src" ]] ; then
        # Resize the image's width to 500px (ffmpeg/imagemagick)
        ffmpeg -i "$src" -vf scale=500:500 "$COVER" &> /dev/null
        #convert "$src" -resize 500x "$COVER" &> /dev/null
        if [[ -f "$COVER" ]] ; then
           # Scale down the cover to 83% of the original
           printf "\e]20;${COVER};83x83+12+00:op=keep-aspect\a"
        else
            reset_background
        fi
    else
        reset_background
    fi
    
} &
