#!/usr/bin/env bash

MUSIC_DIR="$(cat ~/.ncmpcpp/albumart | grep 'mpd_music_dir' | awk -F'"' '{print $2}')"
COVER=/tmp/cover.jpg

function reset_background
{
    printf "\e]20;;100x100+1000+1000\a"
}

{
    album="$(mpc --format %album% current -p 6600)"
    file="$(mpc --format %file% current -p 6600)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    
    # For Album Art
    if [[ -n "$src" ]] ; then
        # Resize the image's width to 300px
        convert "$src" -resize 300x "$COVER"
        if [[ -f "$COVER" ]] ; then
           # Scale down the cover to 62% of the original
           printf "\e]20;${COVER};62x62+87+00:op=keep-aspect\a"
        else
            reset_background
        fi
    else
        reset_background
    fi
    
    # For Notifications
    if [[ -n "$src" ]] ; then
        # Resize the image's width to 70px
        convert "$src" -resize 70x "$COVER"
        ~/.scripts/notify/notify-send.sh -u normal -r 7777 -i ${COVER} "  Now Playing" "`mpc --format '[%artist%\n%title% | %file%]' current`"
    else
        # Fallback
        ~/.scripts/notify/notify-send.sh -u normal -r 7777 -i musique "Now Playing" "`mpc --format '[%artist%\n%title% | %file%]' current`"
    fi
} &
