#!/usr/bin/env bash
source $HOME/.owl4ce_var

run() {
    while true
    do
        mpc current > $NCMPCPP_SCRIPTS_DIR/current-track
        mpc idle &> /dev/null
        [[ "$(cat $NCMPCPP_SCRIPTS_DIR/current-track)" != *"$(mpc current)"* ]] && bash -c "$NCMPCPP_SCRIPTS_DIR/notify"
    done
}

{
    which {mpd,mpc} > /dev/null 2>&1 || exit 1
    if [[ "$(pstree)" = *"mpd"* ]]; then
        run
    else
        mpd &> /dev/null
        run
    fi
} &
