#!/usr/bin/env bash
LC_ALL=C LANG=C; . "${HOME}/.owl4ce_var"

type -p mp{d,c} &>/dev/null || exit 1

run() {
    while :; do
        mpc current > "$MPD_CURRENT_TRACK"
        nice -n 19 mpc idle || mpc idle
        if [[ "$(cat "$MPD_CURRENT_TRACK")" != "$(mpc current)" ]]; then
            "${NCMPCPP_SCRIPTS_DIR}/notify"
        fi
    done
}

{
    if pgrep mpd || pstree | grep -qo mpd; then
        run
    else
        if mpd; then
            run
        else
            exec "$EXNOTIFY_SEND" -u low -r 88888 -i "$NOTIF_MUSIC_ICON" "Music Player" "<span size='small'><u>mpd</u></span>\nFailed to start!"
        fi
    fi
} &>/dev/null &

exit $?
