#!/usr/bin/env bash
LC_ALL=C LANG=C; source "$HOME"/.owl4ce_var

noterr() { echo "Install iproute2/wireless-tools!"; exit 1; }
type -p {"ip","iwgetid"} &> /dev/null || noterr

wifi="" wifi_noip="" wifi_disabled="" lan="" lan_noip="" void=""

if iwgetid "$INT_WIFI" &> /dev/null; then
    if [[ -n "$(iwgetid "$INT_WIFI" | grep -oP '"\K[^"]+')" ]]; then
        if { ip addr show "$INT_WIFI" | grep 'inet'; } &> /dev/null; then
            status="$(iwgetid "$INT_WIFI" --raw)"
            icon="$wifi"
        else
            status="No IP address (${INT_WIFI})"
            icon="$wifi_noip"
        fi
    else
        status="Disconnected"
        icon="$wifi_disabled"
    fi
elif ip link show "$INT_ETH" &> /dev/null; then
    if { ip addr show "$INT_ETH" | grep 'inet'; } &> /dev/null; then
        status="$(ip addr show "$INT_ETH" | grep -oP 'inet \K[^/]+' | head -n1) (${INT_ETH})"
        icon="$lan"
    else
        status="No IP address (${INT_ETH})"
        icon="$lan_noip"
    fi
else
    status="Network interface not found (${INT_ETH}/{$INT_WIFI})"
    icon="$void"
fi

case $1 in
    status) exec echo "$status"
    ;;
    icon)   exec echo "$icon"
    ;;
esac; exit $?
