#!/usr/bin/env bash
source $HOME/.owl4ce_var

temp_dev_path="/sys/devices/virtual/thermal"

[[ -d $temp_dev_path/$TEMP_DEV ]] && \

get_temp() {
    CEL=$'\xc2\xb0C'
    temp="$(cat $temp_dev_path/$TEMP_DEV/temp)"
    temp="$(expr $temp / 1000)"
    echo "$temp$CEL"
}

get_temp || echo "$TEMP_DEV not found!"; exit 1
