#!/usr/bin/env bash
LC_ALL=C LANG=C source $HOME/.owl4ce_var

noterr() { echo "Install alsa-utils!"; exit 1; }
type -p "amixer" &> /dev/null || noterr

CHK_MUTE() { amixer get Master | grep 'off'; }
VOLUME="$(amixer get Master | grep -oP '\[\K[^%\]]+' | head -n1)"

icon() {
    if [[ "$VOLUME" -eq 0 ]]; then
        icon=""
    elif [[ "$VOLUME" -lt 10 ]]; then
        icon=""
    elif [[ "$VOLUME" -lt 30 ]]; then
        icon=""
    elif [[ "$VOLUME" -lt 70 ]]; then
        icon=""
    else
        icon=""
    fi
    
    echo "$icon"
}

case $1 in
    percent)    if CHK_MUTE &> /dev/null; then
                    echo "Muted"
                else
                    echo "$VOLUME%"
                fi
    ;;
    icon)       if CHK_MUTE &> /dev/null; then
                    echo ""
                else
                    icon
                fi
    ;;
    up)         amixer set Master on -q
                amixer sset Master "${AUDIO_STEPS:-5}"%+ -q
    ;;
    down)       amixer set Master on -q
                amixer sset Master "${AUDIO_STEPS:-5}"%- -q
    ;;
    mute)       amixer set Master 1+ toggle -q
    ;;
esac    
