#!/usr/bin/env bash

CURRENT_VOL() { amixer -D pulse get Master | grep '%' | head -n 1 | awk -F'[' '{print $2}' | awk -F'%' '{print $1}'; }
CHK_MUTE() { amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off; }
volume="$(CURRENT_VOL)"

icon() {
    if [ "$volume" = "0" ]; then
        icon=""
    else    
        if [  "$volume" -lt "10" ]; then
            icon=""
        else
            if [ "$volume" -lt "30" ]; then
                icon=""
            else
                if [ "$volume" -lt "70" ]; then
                    icon=""
                else
                    icon=""
                fi
            fi
        fi
    fi
    echo "$icon"
}

case $1 in
    percent)
        if CHK_MUTE &> /dev/null; then
            echo "Muted"
        else
            echo "$volume%"
        fi
    ;;
    icon)
        if CHK_MUTE &> /dev/null; then
            echo ""
        else
            icon
        fi
	;;
    up)
        amixer -D pulse set Master on -q
        # +5%
        amixer -D pulse sset Master 5%+ -q
    ;;
    down)
        amixer -D pulse set Master on -q
        # -5%
        amixer -D pulse sset Master 5%- -q
    ;;
    mute)
        amixer -D pulse set Master 1+ toggle -q
	;;
esac    
