#!/usr/bin/env bash
export LC_ALL=POSIX LANG=POSIX; . "${HOME}/.owl4ce_var"

PARTIALLY()
{
    # Set the openbox menu color from owl4ce_var.
    sed -e "/menu.items.active.text.color/s/:.*/: ${MECH_OB_MENU_ITM}/" \
        -e "/menu.title.text.color/s/:.*/: ${MECH_OB_MENU_TTL}/" -i "${MECH_BUTTON_DIR}/themerc"
    # Set the rofi accent color from owl4ce_var.
    sed -i "/accent/s/:.*;/:           ${MECH_ROFI_ACCENT};/" "${ROFI_COLORSCHEMES_DIR}/fullscreen-dark.rasi"
    sed -e "/foreground/s/:.*;/:       ${MECH_ROFI_FRGRND};/" \
        -e "/accent/s/:.*;/:           ${MECH_ROFI_ACCENT};/" -i "${ROFI_COLORSCHEMES_DIR}/sidebar-dark.rasi"
}

APPLY_ALL()
{
    # Call this first.
    PARTIALLY
    
    # GTK and Icon themes.
    sed -e '/gtk-icon-theme-name/s/=".*"/="Papirus-Dark-Custom"/' \
        -e '/gtk-theme-name/s/=".*"/="Fleon"/' -i "$GTK2_CONFIG"
    sed -e '/gtk-icon-theme-name/s/=.*/=Papirus-Dark-Custom/' \
        -e '/gtk-theme-name/s/=.*/=Fleon/' -i "$GTK3_CONFIG"
    
    # xsettingsd for GTK+ live reload.
    if [ -x "$(command -v xsettingsd)" ]; then
        if [ -f "$XSETTINGSD_CONFIG" ]; then
            sed -e '/Net\/IconThemeName/s/".*"/"Papirus-Dark-Custom"/' \
                -e '/Net\/ThemeName/s/".*"/"Fleon"/' -i "$XSETTINGSD_CONFIG"
        fi; xsettingsd &>/dev/null &
        { read -rt 2 <> <(:) || killall -9 xsettingsd; } &
    fi
    
    # Rofi color schemes.
    sed -i '/@import/s/colorschemes\/.*.rasi/colorschemes\/fullscreen-dark.rasi/' "$ROFI_FULLSCREEN_CONFIG"
    sed -i '/@import/s/colorschemes\/.*.rasi/colorschemes\/sidebar-dark.rasi/' "$ROFI_SIDEBAR_CONFIG"
    
    # Set the Openbox margin, dunst, and rofi sidebar.
    if [ "$CHK_ORT" = 'vertical' ]; then
        sed -i "/vertical=/s/\".*\"/\"${CHK_ORT_V}\"/" "$ORT_FILE"
        "${VISMOD_DIR}/margin-dunst-rofi" v_${CHK_ORT_V}
    elif [ "$CHK_ORT" = 'horizontal' ]; then
        sed -i "/horizontal=/s/\".*\"/\"${CHK_ORT_H}\"/" "$ORT_FILE"
        "${VISMOD_DIR}/margin-dunst-rofi" h_${CHK_ORT_H}
    fi; openbox --reconfigure
    
    # Set the Openbox last button location.
    if [ "$CHK_VISMOD_LOC_BUTTON" = 'left' ]; then
        sed -i '/<titleLayout>/s/>.*</>CIML</' "$OB_CONFIG"
        echo 'left' > "$VISMOD_LOC_BUTTON_FILE"
    elif [ "$CHK_VISMOD_LOC_BUTTON" = 'right' ]; then
        sed -i '/<titleLayout>/s/>.*</>LIMC</' "$OB_CONFIG"
        echo 'right' > "$VISMOD_LOC_BUTTON_FILE"
    fi
    
    # The Openbox buttons and theme.
    cp -f "${OB_BUTTON_DIR}/${CHK_VISMOD_BUTTON}"/* "$MECH_BUTTON_DIR"/.
    THEME_LINE="$(cat -n "$OB_CONFIG" | grep '<name>.*</name>' | sed 1q | grep -oE '[0-9]+')"
    sed -i "${THEME_LINE}s_<name>.*</name>_<name>Fleon</name>_" "$OB_CONFIG"
    
    # Reconfigure Openbox with realistic sync.
    read -rt .4 <> <(:) || exec openbox --reconfigure
}

case ${1} in
    partially) PARTIALLY; exec openbox --reconfigure
    ;;
    *)         APPLY_ALL
    ;;
esac

exit ${?}
