#!/usr/bin/env bash
source $HOME/.owl4ce_var

# Notification Daemon
dunst -config $DUNST_DIR/$CHK_DUNST_MOD &

# Wallpaper Setter
nitrogen --set-zoom-fill --save $WALL_DIR/$CHK_VISMOD_WALL &> /dev/null

# Panel
tint2 -c $TINT2_DIR/$CHK_VISMOD-$CHK_ORT.tint2rc &
