#!/usr/bin/env bash

# Mechanical Theme UI (Minimal Mode)

wall="$(cat ~/.config/openbox/visual-mode/mechanical/wall-minimal)"

# Background Handler
nitrogen --set-zoom-fill --save ~/.wallpaper/mechanical/$wall &> /dev/null

# Panel
tint2 -c ~/.config/tint2/statint-dark.tint2rc &

# Notification Daemon
dunst -config ~/.config/dunst/dunstrc-dark-left &
