#!/usr/bin/env bash
. "${HOME}/.owl4ce_var"

command -v urxvt ncmpcpp &>/dev/null || exit 1

CURRENT_MUSICPL="$("$DEFAPPS_EXEC" -g musicpl)"

if [ "$CURRENT_MUSICPL" = 'mpd' ]; then
    {
        case ${1} in
            albumart)        exec urxvt -g 84x13 -e ncmpcpp -c "${NCMPCPP_DIR}/albumart"
            ;;
            single-albumart) exec urxvt -g 47x18 -e ncmpcpp -c "${NCMPCPP_DIR}/single-albumart"
            ;;
            *)               exec "$DEFAPPS_EXEC" terminal -e ncmpcpp
            ;;
        esac
        
    } &>/dev/null &
else
    exec "$EXNOTIFY_SEND" -u low -r 88888 -i "$NOTIF_MUSIC_ICON" 'Music Player' "<span size='small'><u>${CURRENT_MUSICPL}</u></span>\nCurrently not set to <u>mpd</u>"
fi

exit ${?}
