#!/usr/bin/env bash

# Music (spotify-mpd) controller

current="$(cat ~/.config/openbox/music-player)"

if [[ $current == *"mpd"* ]]; then
    prev="mpc prev"
    toggle="mpc toggle"
    stop="mpc stop"
    next="mpc next"
    status="mpc status"
    title="$(mpc current)"
else
    if [[ $current == *"spotify"* ]]; then
        prev="playerctl -p spotify previous"
        toggle="playerctl -p spotify play-pause"
        stop="playerctl -p spotify stop"
        next="playerctl -p spotify next"
        status="playerctl -p spotify status"
        title="$(playerctl -p spotify metadata -f '{{artist}} - {{title}}')"
    else
        prev=""
        toggle=""
        stop=""
        next=""
        status=""
        title="There is no mpd or spotify installed"
    fi
fi
    
case $1 in
    icon)
    # For playback status on the panel
    # Requires Material (Icomoon) Font
    if [[ $($status) == *"laying"* ]]; then
        echo ""
    else
        echo ""
    fi
    ;;
    prev)
    bash -c "$prev"
    ;;
    toggle)
    bash -c "$toggle"
    ;;
    stop)
    bash -c "$stop" ; ~/.scripts/notify/notify-send.sh -u low -i "~/.icons/gladient/music.png" -r 8888 "Music Player" "Stopped"
    ;;
    next)
    bash -c "$next"
    ;;
    title)
    # For song title on the panel
    echo "$title"
    ;;
    switchpl)
    # Switch music player between mpd and spotify
    if [[ $current == *"mpd"* ]]; then
        echo "spotify" > ~/.config/openbox/music-player
    else
        echo "mpd" > ~/.config/openbox/music-player
    fi
    ~/.scripts/notify/notify-send.sh -u low -i "~/.icons/gladient/music.png" -r 8888 "Music Player" "Set <u>`cat ~/.config/openbox/music-player`</u> as default"
    ;;
esac
