#!/usr/bin/env bash
export LC_ALL=POSIX; . "${HOME}/.owl4ce_var"

type -p scrot &>/dev/null || exec "$EXNOTIFY_SEND" -u low -r 11 'Install scrot!'

{
    [ "${@}" = 'delay' ] && read -rt .21 <> <(:) || :
    
    while :; do
        if [[ "$COPY2CLIP" = 'yes' && -x "$(command -v xclip)" ]]; then
            CLIP='xclip -selection clipboard -target image/png -i $f && '
            STAT='\n(+CLIPBOARD)'
            break
        elif [ "$SAVE_SS" != 'yes' ]; then
            COPY2CLIP='yes'
        else
            break
        fi
    done
    
    if [ "$SAVE_SS" = 'yes' ]; then
        [ -d "${SAVE_DIR}/Screenshots" ] || install -d "${SAVE_DIR}/Screenshots"
        EXEC="${CLIP}mv -f \$f \"${SAVE_DIR}/Screenshots/\""
        SAVE="$(grep -oE '[^/]+$' <<< "$SAVE_DIR")/Screenshots${STAT}"
    else
        EXEC="${CLIP}rm -f \$f"
        SAVE='CLIPBOARD'
    fi
    
    scrot -q "${QUALITY:-75}" -e "$EXEC" || exit 1
    
    exec "$EXNOTIFY_SEND" -u low -r 11 -i "$NOTIF_SS_ICON" '' "<span size='small'><u>${SAVE}</u></span>\nPicture acquired!"
    
} &>/dev/null &

exit ${?}
