#!/usr/bin/env bash

# Take screenshot
# See scrot manual

savedir=~/Pictures

icon="~/.icons/gladient/shot.png"

copy=0
for flag in "$@"
do
  case $flag in
     -C ) copy=1                                ;;
  esac
done
# Begin
rm /tmp/*_scrot*.png


scrot -e 'mv $f /tmp/'
current="$(ls /tmp/ | grep 'scrot**.png')"
mv /tmp/$current $savedir
if [ $copy -eq 1 ]
then
    xclip -selection clipboard -t image/png -i $savedir/$current
fi

notify-send -i $icon -u low "Screenshot" "Saved in\n<u>$savedir/</u>"


exit 0
