#!/usr/bin/env bash
LC_ALL=C LANG=C; . "${HOME}/.owl4ce_var"

noterr() { "$EXNOTIFY_SEND" -u low -r 13 "Install scrot!"; exit 1; }
type -p scrot &>/dev/null || noterr

{
    read -rt .12 <> <(:) || :
    
    while :; do
        if [[ "$COPY2CLIP" = "yes" && -x "$(command -v xclip)" ]]; then
            CLIP="xclip -selection clipboard -target image/png -i '\$f'; "
            STAT="\n(+CLIPBOARD)"
            break
        elif [[ "$SAVE_SS" != "yes" ]]; then
            COPY2CLIP="yes"
        else
            break
        fi
    done
    
    if [[ "$SAVE_SS" = "yes" ]]; then
        [[ ! -d "${SAVE_DIR}/Screenshots" ]] && mkdir -p "${SAVE_DIR}/Screenshots" || :
        EXEC="${CLIP}mv -f '\$f' \"${SAVE_DIR}/Screenshots/\""
        SAVE="$(echo "$SAVE_DIR" | grep -oE '[^/]+$')/Screenshots${STAT}"
    else
        EXEC="${CLIP}rm -f '\$f'"
        SAVE="CLIPBOARD"
    fi
    
    "$EXNOTIFY_SEND" -u low -r 13 -t 1000 -i "$NOTIF_SS_ICON" "" "Taken in ${TIMER_SEC:-5}s .."
    
    scrot -q "${QUALITY:-75}" -d "${TIMER_SEC:-5}" -e "$EXEC" || exit 1
    
    exec "$EXNOTIFY_SEND" -u low -r 13 -i "$NOTIF_SS_ICON" "" "<span size='small'><u>${SAVE}</u></span>\nPicture acquired!"
} &>/dev/null &

exit $?
