#!/usr/bin/env bash
source $HOME/.owl4ce_var

{
    [[ ! -e $SAVE_DIR/Screenshots ]] && mkdir $SAVE_DIR/Screenshots
    sleep .5s
    
    rm /tmp/*_scrot*.png &> /dev/null
    scrot -q $QUALITY -sfbe 'mv $f /tmp/' -l style=dash,width=3,color="#2be491" &> /dev/null && \
    notify-send -t 750 -i $NOTIF_SS_ICON -u low "Screenshot" "Processing captured image"
    
    CURRENT="$(ls /tmp/ | grep 'scrot' | awk -F'.png' '{print $1}')"

    convert /tmp/$CURRENT.png \
    \( +clone -alpha extract -draw 'fill black polygon 0,0 0,8 8,0 fill white circle 8,8 8,0' \
    \( +clone -flip \) -compose Multiply -composite \( +clone -flop \) -compose Multiply -composite \) \
    -alpha off -compose CopyOpacity -composite /tmp/$CURRENT-rounded.png &> /dev/null

    convert /tmp/$CURRENT-rounded.png \( +clone -background black -shadow 25x10+0+5 \) \
    +swap -background none -layers merge +repage /tmp/$CURRENT-shadow.png &> /dev/null

    convert /tmp/$CURRENT-shadow.png -bordercolor $FRAME_COLOR \
    -border 5 $SAVE_DIR/Screenshots/$CURRENT.png &> /dev/null

    rm /tmp/*_scrot*.png &> /dev/null
    [[ -f $SAVE_DIR/Screenshots/$CURRENT.png ]] && \
    notify-send -i $NOTIF_SS_ICON -u low "Screenshot" "Saved in\n<u>$SAVE_DIR/Screenshots/</u>" && \
    [[ -x "$(which "viewnior" 2> /dev/null)" ]] && viewnior $SAVE_DIR/Screenshots/$CURRENT.png &> /dev/null
} &
