#!/usr/bin/env bash
source $HOME/.owl4ce_var

[[ ! -e $SAVE_DIR/Screenshots ]] && mkdir $SAVE_DIR/Screenshots
notify-send -t 1000 -i $NOTIF_SS_ICON -u low "Screenshot" "In $(echo $TIMER_SEC)s .."

rm /tmp/*_scrot*.png
scrot -d $TIMER_SEC -e 'mv $f /tmp/'
current="$(ls /tmp/ | grep 'scrot')"
cp /tmp/$current $SAVE_DIR/Screenshots
rm /tmp/*_scrot*.png

notify-send -i $NOTIF_SS_ICON -u low "Screenshot" "Saved in\n<u>$SAVE_DIR/Screenshots/</u>"
