#!/usr/bin/env bash
export LC_ALL=POSIX LANG=POSIX; . "${HOME}/.owl4ce_var"

PARTIALLY()
{
    # Set the openbox menu color from owl4ce_var.
    sed -e "/menu.items.active.text.color/s/:.*/: ${EYEC_MIN_OB_MENU_ITM}/" \
        -e "/menu.title.text.color/s/:.*/: ${EYEC_MIN_OB_MENU_TTL}/" -i "${EYC_BUTTON_DIR}/themerc"
    # Set the rofi accent color from owl4ce_var.
    sed -i "/accent/s/:.*;/:           ${EYEC_MIN_ROFI_ACCENT};/" "${ROFI_COLORSCHEMES_DIR}/fullscreen.rasi"
    sed -e "/foreground/s/:.*;/:       ${EYEC_MIN_ROFI_FRGRND};/" \
        -e "/accent/s/:.*;/:           ${EYEC_MIN_ROFI_ACCENT};/" -i "${ROFI_COLORSCHEMES_DIR}/sidebar.rasi"
}

APPLY_ALL()
{
    # Call this first.
    PARTIALLY
    
    # GTK and Icon themes.
    sed -e '/gtk-icon-theme-name/s/=".*"/="Papirus-Custom"/' \
        -e '/gtk-theme-name/s/=".*"/="Sweetly"/' -i "$GTK2_CONFIG"
    sed -e '/gtk-icon-theme-name/s/=.*/=Papirus-Custom/' \
        -e '/gtk-theme-name/s/=.*/=Sweetly/' -i "$GTK3_CONFIG"
    
    # xsettingsd for GTK+ live reload.
    if [ -x "$(command -v xsettingsd)" ]; then
        if [ -f "$XSETTINGSD_CONFIG" ]; then
            sed -e '/Net\/IconThemeName/s/".*"/"Papirus-Custom"/' \
                -e '/Net\/ThemeName/s/".*"/"Sweetly"/' -i "$XSETTINGSD_CONFIG"
        fi; xsettingsd &>/dev/null &
        { read -rt 2 <> <(:) || killall -9 xsettingsd; } &
    fi
    
    # Rofi color schemes.
    sed -i '/@import/s/colorschemes\/.*.rasi/colorschemes\/fullscreen.rasi/' "$ROFI_FULLSCREEN_CONFIG"
    sed -i '/@import/s/colorschemes\/.*.rasi/colorschemes\/sidebar.rasi/' "$ROFI_SIDEBAR_CONFIG"
    
    # Set the Openbox margin.
    { "${VISMOD_DIR}/margin-dunst-rofi" minmod && openbox --reconfigure; } &>/dev/null
    
    # Set the Openbox last button location.
    if [ "$CHK_MINMOD_LOC_BUTTON" = 'left' ]; then
        sed -i '/<titleLayout>/s/>.*</>CIML</' "$OB_CONFIG"
        echo 'left' > "$MINMOD_LOC_BUTTON_FILE"
    elif [ "$CHK_MINMOD_LOC_BUTTON" = 'right' ]; then
        sed -i '/<titleLayout>/s/>.*</>LIMC</' "$OB_CONFIG"
        echo 'right' > "$MINMOD_LOC_BUTTON_FILE"
    fi

    # The Openbox buttons and theme.
    cp -f "${OB_BUTTON_DIR}/${CHK_MINMOD_BUTTON}"/* "$EYC_BUTTON_DIR"/.
    THEME_LINE="$(cat -n "$OB_CONFIG" | grep '<name>.*</name>' | sed 1q | grep -oE '[0-9]+')"
    sed -i "${THEME_LINE}s_<name>.*</name>_<name>Sweetly</name>_" "$OB_CONFIG"
    
    # Reconfigure Openbox with realistic sync.
    read -rt .4 <> <(:) || exec openbox --reconfigure
}

case ${1} in
    partially) PARTIALLY; exec openbox --reconfigure
    ;;
    *)         APPLY_ALL
    ;;
esac

exit ${?}
