#!/usr/bin/env bash
LC_ALL=C LANG=C source $HOME/.owl4ce_var

PARTIALLY() {
    # Set Openbox Colors from owl4ce_var
    sed -i "s/menu.title.text.color:.*/menu.title.text.color: $EYEC_MIN_OB_MENU_TTL/" $THEME_DIR/Sweetly/openbox-3/themerc
    sed -i "s/menu.items.active.text.color:.*/menu.items.active.text.color: $EYEC_MIN_OB_MENU_ITM/" $THEME_DIR/Sweetly/openbox-3/themerc
    
    # Set Rofi Accent Color from owl4ce_var
    sed -i "2s_accent:.*;_accent:           $EYEC_MIN_ROFI_ACCENT;_" $ROFI_COLORSCHEMES_DIR/fullscreen.rasi
    sed -i "2s_accent:.*;_accent:           $EYEC_MIN_ROFI_ACCENT;_" $ROFI_COLORSCHEMES_DIR/sidebar.rasi
    sed -i "5s_foreground:.*;_foreground:       $EYEC_MIN_ROFI_FRGRND;_" $ROFI_COLORSCHEMES_DIR/sidebar.rasi
}

ALL() {
    PARTIALLY
    # GTK Theme
    sed -i '5s_gtk-theme-name=.*_gtk-theme-name="Sweetly"_' $GTK2_CONFIG
    sed -i '10s_gtk-theme-name=.*_gtk-theme-name=Sweetly_' $GTK3_CONFIG
    sed -i '1s_Net/IconThemeName.*_Net/IconThemeName "Papirus-Custom"_' $XSETTINGSD_CONFIG
    sed -i '2s_Net/ThemeName.*_Net/ThemeName "Sweetly"_' $XSETTINGSD_CONFIG
    xsettingsd &> /dev/null &
    read -rt "3" <> <(:) || killall xsettingsd &
    
    # Set Openbox Margin
    "$VISMOD_DIR/margin-dunst-rofi" minmod &> /dev/null
    openbox --reconfigure
    
    # Icon Theme
    sed -i '6s_gtk-icon-theme-name=.*_gtk-icon-theme-name="Papirus-Custom"_' $GTK2_CONFIG
    sed -i '8s_gtk-icon-theme-name=.*_gtk-icon-theme-name=Papirus-Custom_' $GTK3_CONFIG
    
    # Rofi Color Scheme
    sed -i '5s_colorschemes/.*.rasi_colorschemes/fullscreen.rasi_' $ROFI_FULLSCREEN_CONFIG
    sed -i '5s_colorschemes/.*.rasi_colorschemes/sidebar.rasi_' $ROFI_SIDEBAR_CONFIG
    
    # Set Openbox Last Button Location
    if [[ $CHK_MINMOD_LOC_BUTTON = *"left"* ]]; then
        sed -i '35s_<titleLayout>.*_<titleLayout>CIML</titleLayout>_' $OB_CONFIG
        echo "left" > $MINMOD_LOC_BUTTON_FILE
    elif [[ $CHK_MINMOD_LOC_BUTTON = *"right"* ]]; then
        sed -i '35s_<titleLayout>.*_<titleLayout>LIMC</titleLayout>_' $OB_CONFIG
        echo "right" > $MINMOD_LOC_BUTTON_FILE
    fi

    # Openbox Theme & Buttons
    cp "$OB_BUTTON_DIR"/"$CHK_MINMOD_BUTTON"/* $EYC_BUTTON_DIR
    sed -i '34s_<name>.*_<name>Sweetly</name>_' $OB_CONFIG
    
    # Reconfigure Openbox (realistic theme)
    read -rt ".4" <> <(:) || openbox --reconfigure &
}

case $1 in
    partially)  PARTIALLY
                openbox --reconfigure
    ;;
    *)          ALL
    ;;
esac
