#!/usr/bin/env bash
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#
# ---
. "${HOME}/.owl4ce_var"

# There was once a pulseaudio here.

# UI appearance.
{ "${VISMOD_DIR}/mode-toggle" just_ui && "$OB_TRAY"; } 2>/dev/null

# Compositor.
picom -b 2>/dev/null

# Authentication agent (PolicyKit).
if [ -x "$(command -v lxpolkit)" ]; then
    lxpolkit 2>/dev/null &
elif [ -x "/usr/libexec/polkit-gnome-authentication-agent-1" ]; then
    /usr/libexec/polkit-gnome-authentication-agent-1 2>/dev/null &
fi

# Session auto-locker.
xautolock -time "$AUTOLOCK_MINUTE" -locker "$("$DEFAPPS_EXEC" -g lockscreen)" -detectsleep -resetsaver -corners 00-- -cornersize 1000 \
-notifier "${EXNOTIFY_SEND} -i ${ICON_GLADIENT_DIR}/lock.png 'Lockscreen' 'Will be locked in 5s from now!'" -notify 5 2>/dev/null &

# Start the MPD player (+notification-sender).
"$MPD_TCD"
