#!/usr/bin/env sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#
# ---
source $HOME/.owl4ce_var

# there was once a pulseaudio here

# UI Appearance
bash -c "$VISMOD_DIR/mode-toggle startup"

# Compositor
picom -b &> /dev/null &

# Authentication Agent - PolicyKit
lxpolkit &> /dev/null &

# Power Manager
xfce4-power-manager &> /dev/null &

# Sessions Autolock
xautolock -time $AUTOLOCK_MINUTE -locker "$($DEFAPPS_EXEC -g lockscreen)" -detectsleep -resetsaver -corners 00-- -cornersize 1000 \
-notifier "$EXNOTIFY_SEND -i $ICON_GLADIENT_DIR/lock.png 'Lockscreen' 'Will be locked in 5s from now'" -notify 5 &> /dev/null &

# Start mpd if defined as default music player
[[ "$($DEFAPPS_EXEC -g musicpl)" = "mpd" ]] && \
bash -c "$MPD_TCD"
